name: CI
on:
  push: 
    branches: "main"
  pull_request: 
    branches: "main"
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo fmt --check
