name: CI
on:
  push: 
    branches: "main"
  pull_request: 
    branches: "main"
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo fmt --check
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo clippy -- -D warnings
  test:
    strategy:
      fail-fast: false
      matrix: 
        os: [ubuntu-latest,macos-latest,windows-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@nextest
      - run: cargo nextest run
    
  all-systems-pass:
    runs-on: ubuntu-latest
    needs: [format,clippy,test]
    steps:
      - uses: actions/checkout@v4
